"""Ukloni amount kolonu iz Project modela

Revision ID: 00d8b5a37d00
Revises: c5e74b350781
Create Date: 2025-03-13 21:04:14.020033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00d8b5a37d00'
down_revision = 'c5e74b350781'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.NUMERIC(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###
