"""dodata kolona note u Invoice

Revision ID: 07516a85331b
Revises: 7462a2a52443
Create Date: 2025-05-13 15:27:44.065831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07516a85331b'
down_revision = '7462a2a52443'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_column('note')

    # ### end Alembic commands ###
