"""dodata kolona sub_account_number u BankAccount

Revision ID: 0e48a68791fe
Revises: 4cc06ff15fc0
Create Date: 2025-05-04 14:45:36.835238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e48a68791fe'
down_revision = '4cc06ff15fc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sub_account_number', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_account', schema=None) as batch_op:
        batch_op.drop_column('sub_account_number')

    # ### end Alembic commands ###
