"""Izmene u ArchiveSettings modelu: fax preimenovan u phone_2

Revision ID: 1b00ef4fbbcd
Revises: 83d636880cde
Create Date: 2025-03-22 11:14:04.073682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b00ef4fbbcd'
down_revision = '83d636880cde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archive_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_1', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('phone_2', sa.String(length=20), nullable=True))
        batch_op.drop_column('fax')
        batch_op.drop_column('phones')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archive_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phones', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('fax', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_column('phone_2')
        batch_op.drop_column('phone_1')

    # ### end Alembic commands ###
