"""ArchiveSettings nova polja

Revision ID: 3345819613eb
Revises: 50bfa23effd9
Create Date: 2025-03-16 08:49:07.434859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3345819613eb'
down_revision = '50bfa23effd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archive_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zip_code', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('phones', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('fax', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('web_site', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archive_settings', schema=None) as batch_op:
        batch_op.drop_column('web_site')
        batch_op.drop_column('email')
        batch_op.drop_column('fax')
        batch_op.drop_column('phones')
        batch_op.drop_column('zip_code')

    # ### end Alembic commands ###
