"""dodato document_number u Invoice

Revision ID: 445fc3a96875
Revises: 07516a85331b
Create Date: 2025-05-15 20:14:50.728032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '445fc3a96875'
down_revision = '07516a85331b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_number', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_column('document_number')

    # ### end Alembic commands ###
