"""Partner dodata kolona contry

Revision ID: 50bfa23effd9
Revises: 86b40fd1d60e
Create Date: 2025-03-13 22:41:46.563772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50bfa23effd9'
down_revision = '86b40fd1d60e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partner', schema=None) as batch_op:
        batch_op.drop_column('country')

    # ### end Alembic commands ###
