"""StatementItem izmene

Revision ID: 6275532173a4
Revises: d5203fdd2c37
Create Date: 2025-03-25 10:59:31.634529

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6275532173a4'
down_revision = 'd5203fdd2c37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('statement_item', schema=None) as batch_op:
        batch_op.drop_constraint('statement_item_ibfk_5', type_='foreignkey')
        batch_op.drop_column('invoice_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('statement_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('statement_item_ibfk_5', 'invoice', ['invoice_id'], ['id'])

    # ### end Alembic commands ###
