"""status fakture

Revision ID: 81d386770305
Revises: 6275532173a4
Create Date: 2025-03-26 09:53:18.088312

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '81d386770305'
down_revision = '6275532173a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.drop_column('payment_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_status', mysql.VARCHAR(length=20), nullable=True))
        batch_op.drop_column('status')

    # ### end Alembic commands ###
