"""Izmene u ArchiveSettings modelu: dodat model i poziv_na_broj, uklonjen use_eur

Revision ID: 83d636880cde
Revises: c04811084962
Create Date: 2025-03-22 10:57:20.783729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83d636880cde'
down_revision = 'c04811084962'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archive_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('poziv_na_broj', sa.String(length=20), nullable=True))
        batch_op.alter_column('pib',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=9),
               existing_nullable=True)
        batch_op.alter_column('mb',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=8),
               existing_nullable=True)
        batch_op.drop_column('use_eur')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archive_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('use_eur', sa.BOOLEAN(), nullable=False))
        batch_op.alter_column('mb',
               existing_type=sa.String(length=8),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('pib',
               existing_type=sa.String(length=9),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.drop_column('poziv_na_broj')
        batch_op.drop_column('model')

    # ### end Alembic commands ###
