"""ArchiveSettings izmene kolona

Revision ID: 86b40fd1d60e
Revises: 00d8b5a37d00
Create Date: 2025-03-13 21:40:18.907239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86b40fd1d60e'
down_revision = '00d8b5a37d00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archive_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eur_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('eur_rate_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archive_settings', schema=None) as batch_op:
        batch_op.drop_column('country')
        batch_op.drop_column('city')
        batch_op.drop_column('eur_rate_date')
        batch_op.drop_column('eur_rate')

    # ### end Alembic commands ###
