"""izmene u Service

Revision ID: 964f369b1241
Revises: 3ed293c64d2e
Create Date: 2025-02-16 11:53:20.233244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '964f369b1241'
down_revision = '3ed293c64d2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_unit_of_measure', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_column('service_unit_of_measure')

    # ### end Alembic commands ###
