"""Povezivanje BankAccount i BankStatement

Revision ID: bbbc8dba575b
Revises: 81d386770305
Create Date: 2025-03-27 11:42:21.125948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbbc8dba575b'
down_revision = '81d386770305'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_statement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_account_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'bank_account', ['bank_account_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_statement', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('bank_account_id')

    # ### end Alembic commands ###
