"""Vracanje phones kolone umesto phone i phone2

Revision ID: c5e74b350781
Revises: ede5aeedd92a
Create Date: 2025-03-02 13:12:56.055680

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text


# revision identifiers, used by Alembic.
revision = 'c5e74b350781'
down_revision = 'ede5aeedd92a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_partner')
    with op.batch_alter_table('partner', schema=None) as batch_op:
        # Prvo dodajemo active kolonu sa default vrednošću True
        batch_op.add_column(sa.Column('active', sa.Boolean(), server_default=sa.text('1'), nullable=False))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_nullable=False,
               server_default=text("''"))
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('account_number',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('customer',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               server_default=sa.text('0'))
        batch_op.alter_column('supplier',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               server_default=sa.text('0'))
        batch_op.alter_column('international',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               server_default=sa.text('0'))
        batch_op.drop_column('country')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False, server_default=text("''")))
        batch_op.add_column(sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('note', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=True))
        batch_op.alter_column('archived',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               server_default=sa.text('0'))
        batch_op.drop_column('project_description')
        batch_op.drop_column('project_value')
        batch_op.drop_column('project_year')
        batch_op.drop_column('project_name')

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_sr', sa.String(length=100), nullable=False, server_default=text("''")))
        batch_op.add_column(sa.Column('name_en', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('note', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('unit_of_measure_id', sa.Integer(), nullable=False, server_default=text("0")))
        batch_op.add_column(sa.Column('price_rsd', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('price_eur', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.alter_column('archived',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               server_default=sa.text('0'))
        batch_op.create_foreign_key('fk_service_unit_of_measure', 'unit_of_measure', ['unit_of_measure_id'], ['id'])
        batch_op.drop_column('service_unit_of_measure')
        batch_op.drop_column('service_name_en')
        batch_op.drop_column('service_description')
        batch_op.drop_column('service_name_rs')
        batch_op.drop_column('service_value')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('user_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_type', sa.VARCHAR(length=20), nullable=False))

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_value', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('service_name_rs', sa.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('service_description', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('service_name_en', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('service_unit_of_measure', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_constraint('fk_service_unit_of_measure', type_='foreignkey')
        batch_op.alter_column('archived',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.drop_column('price_eur')
        batch_op.drop_column('price_rsd')
        batch_op.drop_column('unit_of_measure_id')
        batch_op.drop_column('note')
        batch_op.drop_column('name_en')
        batch_op.drop_column('name_sr')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_name', sa.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('project_year', sa.VARCHAR(length=4), nullable=True))
        batch_op.add_column(sa.Column('project_value', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('project_description', sa.VARCHAR(length=200), nullable=True))
        batch_op.alter_column('archived',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.drop_column('year')
        batch_op.drop_column('note')
        batch_op.drop_column('amount')
        batch_op.drop_column('name')

    with op.batch_alter_table('partner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.VARCHAR(length=20), nullable=True))
        batch_op.alter_column('international',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('supplier',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('customer',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('account_number',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('city',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('active')

    op.create_table('_alembic_tmp_partner',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('account_number', sa.VARCHAR(length=50), nullable=True),
    sa.Column('international', sa.BOOLEAN(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('address', sa.VARCHAR(length=200), nullable=True),
    sa.Column('city', sa.VARCHAR(length=50), nullable=True),
    sa.Column('pib', sa.VARCHAR(length=20), nullable=True),
    sa.Column('mb', sa.VARCHAR(length=20), nullable=True),
    sa.Column('fax', sa.VARCHAR(length=20), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('customer', sa.BOOLEAN(), nullable=False),
    sa.Column('supplier', sa.BOOLEAN(), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('phone2', sa.VARCHAR(length=20), nullable=True),
    sa.Column('active', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
