"""uvećan decimal

Revision ID: d11cef134645
Revises: 445fc3a96875
Create Date: 2025-10-15 16:41:07.243033

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd11cef134645'
down_revision = '445fc3a96875'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_statement', schema=None) as batch_op:
        batch_op.alter_column('initial_balance',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
        batch_op.alter_column('total_credit',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
        batch_op.alter_column('total_debit',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
        batch_op.alter_column('final_balance',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.alter_column('total_amount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('invoice_item', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
        batch_op.alter_column('price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
        batch_op.alter_column('total',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('project_account', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('purchase_plan_account', schema=None) as batch_op:
        batch_op.alter_column('amount_1',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
        batch_op.alter_column('amount_2',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.alter_column('price_rsd',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
        batch_op.alter_column('price_eur',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('statement_item', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('statement_item', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.alter_column('price_eur',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('price_rsd',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('purchase_plan_account', schema=None) as batch_op:
        batch_op.alter_column('amount_2',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('amount_1',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('project_account', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('invoice_item', schema=None) as batch_op:
        batch_op.alter_column('total',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('price',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('quantity',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.alter_column('total_amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('bank_statement', schema=None) as batch_op:
        batch_op.alter_column('final_balance',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('total_debit',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('total_credit',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('initial_balance',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###
