"""rename phones and fax to phone_1 and phone_2

Revision ID: d5203fdd2c37
Revises: c8328e7057b5_fixed
Create Date: 2025-03-22 13:41:52.608429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5203fdd2c37'
down_revision = 'c8328e7057b5_fixed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_1', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('phone_2', sa.String(length=20), nullable=True))
    
    # Kopiranje podataka iz phones u phone_1 i iz fax u phone_2
    conn = op.get_bind()
    conn.execute(sa.text("UPDATE partner SET phone_1 = phones, phone_2 = fax"))
    
    with op.batch_alter_table('partner', schema=None) as batch_op:
        batch_op.drop_column('fax')
        batch_op.drop_column('phones')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phones', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('fax', sa.VARCHAR(length=20), nullable=True))
    
    # Kopiranje podataka iz phone_1 u phones i iz phone_2 u fax
    conn = op.get_bind()
    conn.execute(sa.text("UPDATE partner SET phones = phone_1, fax = phone_2"))
    
    with op.batch_alter_table('partner', schema=None) as batch_op:
        batch_op.drop_column('phone_2')
        batch_op.drop_column('phone_1')

    # ### end Alembic commands ###
