"""StatementItem izmene

Revision ID: de5e3fb07569
Revises: d5203fdd2c37
Create Date: 2025-03-25 09:33:52.878007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de5e3fb07569'
down_revision = 'd5203fdd2c37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('statement_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_procurement', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('payer', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('recipient', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('reference_number', sa.String(length=50), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('invoice_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('statement_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'invoice', ['invoice_id'], ['id'])
        batch_op.drop_column('reference_number')
        batch_op.drop_column('recipient')
        batch_op.drop_column('payer')
        batch_op.drop_column('public_procurement')

    # ### end Alembic commands ###
