"""Dodate tabele PurchasePlan i PurchasePlanAccount

Revision ID: e406bea110f1
Revises: bbbc8dba575b
Create Date: 2025-03-28 16:13:02.526665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e406bea110f1'
down_revision = 'bbbc8dba575b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year')
    )
    op.create_table('purchase_plan_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_plan_id', sa.Integer(), nullable=False),
    sa.Column('account_level_4_number', sa.String(length=4), nullable=False),
    sa.Column('amount_1', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('amount_2', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['purchase_plan_id'], ['purchase_plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_plan_account', schema=None) as batch_op:
        batch_op.create_index('idx_account_level_4_number', ['account_level_4_number'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_plan_account', schema=None) as batch_op:
        batch_op.drop_index('idx_account_level_4_number')

    op.drop_table('purchase_plan_account')
    op.drop_table('purchase_plan')
    # ### end Alembic commands ###
