"""Ažuriranje modela za ER dijagram

Revision ID: ede5aeedd92a
Revises: 964f369b1241
Create Date: 2025-03-02 12:58:41.331901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ede5aeedd92a'
down_revision = '964f369b1241'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_level_4',
    sa.Column('number', sa.String(length=4), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('number')
    )
    op.create_table('archive_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('pib', sa.String(length=20), nullable=True),
    sa.Column('mb', sa.String(length=20), nullable=True),
    sa.Column('logo', sa.String(length=100), nullable=True),
    sa.Column('stamp', sa.String(length=100), nullable=True),
    sa.Column('facsimile', sa.String(length=100), nullable=True),
    sa.Column('use_eur', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bank_statement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('statement_number', sa.String(length=20), nullable=False),
    sa.Column('initial_balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_credit', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_debit', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('final_balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unit_of_measure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_sr', sa.String(length=50), nullable=False),
    sa.Column('name_en', sa.String(length=50), nullable=True),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account_level_6',
    sa.Column('number', sa.String(length=6), nullable=False),
    sa.Column('account_level_4_number', sa.String(length=4), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['account_level_4_number'], ['account_level_4.number'], ),
    sa.PrimaryKeyConstraint('number')
    )
    op.create_table('bank_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('settings_id', sa.Integer(), nullable=False),
    sa.Column('account_number', sa.String(length=50), nullable=False),
    sa.Column('bank', sa.String(length=100), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['settings_id'], ['archive_settings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('service_date', sa.Date(), nullable=False),
    sa.Column('payment_due_date', sa.Date(), nullable=True),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('paid', sa.Boolean(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('incoming', sa.Boolean(), nullable=False),
    sa.Column('payment_status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['partner.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('account_level_6_number', sa.String(length=6), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['account_level_6_number'], ['account_level_6.number'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('statement_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_statement_id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=True),
    sa.Column('account_level_6_number', sa.String(length=6), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_debit', sa.Boolean(), nullable=False),
    sa.Column('document_number', sa.String(length=50), nullable=True),
    sa.Column('account_in_project', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['account_level_6_number'], ['account_level_6.number'], ),
    sa.ForeignKeyConstraint(['bank_statement_id'], ['bank_statement.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['partner.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('archive')
    with op.batch_alter_table('partner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('phone2', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=False))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('account_number',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('customer',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('supplier',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('international',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.drop_column('phones')
        batch_op.drop_column('country')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('note', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=True))
        batch_op.alter_column('archived',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.drop_column('project_value')
        batch_op.drop_column('project_description')
        batch_op.drop_column('project_name')
        batch_op.drop_column('project_year')

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_sr', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('name_en', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('note', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('unit_of_measure_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('price_rsd', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('price_eur', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.alter_column('archived',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.create_foreign_key(None, 'unit_of_measure', ['unit_of_measure_id'], ['id'])
        batch_op.drop_column('service_unit_of_measure')
        batch_op.drop_column('service_description')
        batch_op.drop_column('service_value')
        batch_op.drop_column('service_name_en')
        batch_op.drop_column('service_name_rs')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('user_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_type', sa.VARCHAR(length=20), nullable=False))

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_name_rs', sa.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('service_name_en', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('service_value', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('service_description', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('service_unit_of_measure', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('archived',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.drop_column('price_eur')
        batch_op.drop_column('price_rsd')
        batch_op.drop_column('unit_of_measure_id')
        batch_op.drop_column('note')
        batch_op.drop_column('name_en')
        batch_op.drop_column('name_sr')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_year', sa.VARCHAR(length=4), nullable=True))
        batch_op.add_column(sa.Column('project_name', sa.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('project_description', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('project_value', sa.VARCHAR(length=20), nullable=True))
        batch_op.alter_column('archived',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.drop_column('year')
        batch_op.drop_column('note')
        batch_op.drop_column('amount')
        batch_op.drop_column('name')

    with op.batch_alter_table('partner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('phones', sa.VARCHAR(length=20), nullable=True))
        batch_op.alter_column('international',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('supplier',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('customer',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('account_number',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('city',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('active')
        batch_op.drop_column('phone2')
        batch_op.drop_column('phone')

    op.create_table('archive',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=20), nullable=False),
    sa.Column('address', sa.VARCHAR(length=200), nullable=True),
    sa.Column('pib', sa.VARCHAR(length=20), nullable=True),
    sa.Column('mb', sa.VARCHAR(length=20), nullable=True),
    sa.Column('city', sa.VARCHAR(length=20), nullable=True),
    sa.Column('country', sa.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('statement_item')
    op.drop_table('project_account')
    op.drop_table('invoice_item')
    op.drop_table('invoice')
    op.drop_table('bank_account')
    op.drop_table('account_level_6')
    op.drop_table('unit_of_measure')
    op.drop_table('bank_statement')
    op.drop_table('archive_settings')
    op.drop_table('account_level_4')
    # ### end Alembic commands ###
